@local = http://localhost:3900/api 
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzQ1ZmMwYWI3MzU0MzIyNTIxZmIzZjQiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjY1NTMwODk2LCJleHAiOjE2NjU3MDM2OTZ9.hRXKLuhDKbwz-jaDAQVHbebPFkFgRNVUdnyoU_s985g

//Registration
POST {{local}}/admin/register
Content-Type: application/json

{
  "user_id": "1234567",
  "username": "avrian",
  "password": "123456"
}

###
POST {{local}}/admin/login
Content-Type: application/json

{
  "user_id": "1234567",
  "password": "123456"
}



